#install.packages("ggplot2", dependencies = T)
#install.packages("rgdal", dependencies = T)
#install.packages("RColorBrewer", dependencies = T)
library(ggplot2)
library(rgdal)
library(RColorBrewer)
pa <- readOGR('../diego/worksparce/r/criando_mapas/pa_municipios', '15MUE250GC_SIR')
partos<-read.csv('../diego/worksparce/r/criando_mapas/A092516189_82_30_36.csv', sep = ';', head = T, dec = ',')
partos<-na.omit(partos)
names(partos)[2]<-c("PartosNormais")
partos$CD_GEOCMU<-substr(partos$Municipio, 1, 6)
partos<-partos[order(partos$CD_GEOCMU),]
malhas<-pa@data[order(pa$CD_GEOCMU),]
malhas$CD_GEOCMU<-substr(malhas$CD_GEOCMU, 1, 6)
pa_2<-merge(malhas, partos, by="CD_GEOCMU")
pa.f<-fortify(pa, region = "CD_GEOCMU")
#head(pa.f)
pa_2$partosnormaisCat<-cut(pa_2$PartosNormais, breaks = c(0,10,20,30,40,50,100), labels = c("0 a 10%", "10 a 20%", "20 a 30%", "30 a 40%", "40 a 50%", "50 a 100%"), include.lowest = TRUE)
names(pa_2)[1]<-c("id")
pa.f$id<-substr(pa.f$id, 1, 6)
pa.f<-merge(pa.f, pa_2, by.y="id")
head(pa.f)
ggplot(pa.f, aes(pa.f$long, pa.f$lat, group=pa.f$group, fill=pa.f$partosnormaisCat)) + geom_polygon(colour="black") + coord_equal() + labs(x="Longitude", y="Latitude", fill="% partos normais") + scale_fill_manual(values = brewer.pal(9, "Greens")[4:9])